language: go
go:
  - 1.7
  - 1.6
sudo: true
addons:
  apt:
    packages:
      - gcc-4.6
      - libcurl4-openssl-dev
      - libjansson-dev
      - linux-libc-dev
      - libtool
      - make
      - cmake
      - autoconf
      - git
      - bzip2
script:
  - make test
  - make cover
  - cd nss-octopass && sudo make test; sudo make clean
after_script:
  - goveralls -coverprofile=coverage.out
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
