language: go
go:
  - 1.7
  - 1.6
sudo: true
addons:
  apt:
    packages:
      - gcc-4.6
      - libcurl4-openssl-dev
      - libjansson-dev
      - linux-libc-dev
      - libtool
      - make
      - cmake
      - autoconf
      - git
      - bzip2
script:
  - export BUILD_DIR=$TRAVIS_BUILD_DIR
  - export TRAVIS_BUILD_DIR=$BUILD_DIR/cli
  - pushd ./cli && make test; make cover; popd
  - export TRAVIS_BUILD_DIR=$BUILD_DIR/nss
  - pushd ./nss && sudo make test; sudo make clean; popd
after_script:
  - goveralls -coverprofile=coverage.out
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
