language: c
compiler:
  - gcc
  - clang
sudo: true
addons:
  apt:
    packages:
      - gcc-4.6
      - libcurl4-openssl-dev
      - libjansson-dev
      - linux-libc-dev
      - libtool
      - make
      - autoconf
      - git
      - bzip2
      - clang-format-3.4
script:
  - sudo make test
  - sudo make format
  - sudo make && sudo make install && sudo mv octopass.conf.example /etc/octopass.conf
  - sudo find / -name "libnss*"
  - sudo ln -sf /usr/lib/libnss_octopass.so.2.0 /usr/lib/x86_64-linux-gnu/libnss_octopass.so.2.0
  - octopass passwd linyows
  - getent passwd
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
