language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - gcc-4.6
      - libcurl4-openssl-dev
      - libjansson-dev
      - linux-libc-dev
      - libtool
      - make
      - autoconf
      - git
      - bzip2
script:
  - make test && make clean
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
